const char* lu259_cl =
"#define BLOCK_SIZE 32\n"
"#define BLOCK_SIZE_SUB 64\n"
"__kernel void\n"
"LUFact(\n"
"__global float* A,\n"
"__global float* denom,\n"
"__global float* nextDenom,\n"
"int n,\n"
"int N)\n"
"{\n"
"int row = get_group_id(0) + n+1;\n"
"int item = get_local_id(0);\n"
"int cStart = item * BLOCK_SIZE;\n"
"int cEnd = cStart + BLOCK_SIZE;\n"
"int rStart = row*N;\n"
"int nStart = n*N;\n"
"float lval = A[rStart+n]/(*denom);\n"
"barrier(CLK_GLOBAL_MEM_FENCE);\n"
"if (item == 0)\n"
"A[rStart+n] = lval;\n"
"lval = -lval;\n"
"int i = (n+1) < cStart ? cStart : (n+1);\n"
"if(i > cStart && i < cEnd)\n"
"for(; i%4 != 0; i++)\n"
"A[rStart+i] += lval*A[nStart+i];\n"
"for(; i < cEnd; i+=4)\n"
"{\n"
"A[rStart+i] += lval*A[nStart+i];\n"
"A[rStart+i+1] += lval*A[nStart+i+1];\n"
"A[rStart+i+2] += lval*A[nStart+i+2];\n"
"A[rStart+i+3] += lval*A[nStart+i+3];\n"
"}\n"
"if(row == (n+1) && cStart <= (n+1) && cEnd > n+1)\n"
"*nextDenom = A[rStart+n+1];\n"
"}\n"
"__kernel void\n"
"fSub(\n"
"__global float* A,\n"
"__global float* y,\n"
"__global float* yPart,\n"
"int n,\n"
"int N)\n"
"{\n"
"int t = get_global_id(0);\n"
"int cStart = t*BLOCK_SIZE;\n"
"int cEnd = cStart+BLOCK_SIZE;\n"
"float pSum = 0;\n"
"int e = cEnd < n ? cEnd : n;\n"
"for(int i = cStart; i < e; i++)\n"
"pSum += A[n*N+i]*y[i];\n"
"yPart[t] = pSum;\n"
"}\n"
"__kernel void\n"
"bSub(\n"
"__global float* A,\n"
"__global float* x,\n"
"__global float* xPart,\n"
"int n,\n"
"int N)\n"
"{\n"
"int t = get_global_id(0);\n"
"int cStart = t*BLOCK_SIZE_SUB;\n"
"int cEnd = cStart+BLOCK_SIZE_SUB;\n"
"float pSum = 0;\n"
"int i = (n+1) < cStart ? cStart : (n+1);\n"
"for(; i < cEnd; i++)\n"
"pSum += A[n*N+i]*x[i];\n"
"xPart[t] = pSum;\n"
"}\n"
;
