const char* lu259_cl =
"#define BLOCK_SIZE 64\n"
"#define BLOCK_SIZE_SUB 64\n"
"__kernel void\n"
"LUFact(\n"
"__global double* A,\n"
"__global double* denom,\n"
"__global double* nextDenom,\n"
"int n,\n"
"int N)\n"
"{\n"
"int row = get_group_id(0) + n+1;\n"
"int item = get_local_id(0);\n"
"int cStart = item * BLOCK_SIZE;\n"
"int cEnd = cStart + BLOCK_SIZE;\n"
"double lval = A[row*N+n]/(*denom);\n"
"barrier(CLK_GLOBAL_MEM_FENCE);\n"
"if (item == 0)\n"
"A[row*N+n] = lval;\n"
"lval = -lval;\n"
"int i = (n+1) < cStart ? cStart : (n+1);\n"
"for(; i < cEnd; i++)\n"
"A[row*N+i] += lval*A[n*N+i];\n"
"if(row == (n+1) && cStart <= n+1 && cEnd > n+1)\n"
"*nextDenom = A[(n+1)*N+n+1];\n"
"}\n"
"__kernel void\n"
"fSub(\n"
"__global double* A,\n"
"__global double* y,\n"
"__global double* yPart,\n"
"int n,\n"
"int N)\n"
"{\n"
"int t = get_global_id(0);\n"
"int cStart = t*BLOCK_SIZE;\n"
"int cEnd = cStart+BLOCK_SIZE;\n"
"double pSum = 0;\n"
"int e = cEnd < n ? cEnd : n;\n"
"for(int i = cStart; i < e; i++)\n"
"pSum += A[n*N+i]*y[i];\n"
"yPart[t] = pSum;\n"
"}\n"
"__kernel void\n"
"bSub(\n"
"__global double* A,\n"
"__global double* x,\n"
"__global double* xPart,\n"
"int n,\n"
"int N)\n"
"{\n"
"int t = get_global_id(0);\n"
"int cStart = t*BLOCK_SIZE_SUB;\n"
"int cEnd = cStart+BLOCK_SIZE_SUB;\n"
"double pSum = 0;\n"
"int i = (n+1) < cStart ? cStart : (n+1);\n"
"for(; i < cEnd; i++)\n"
"pSum += A[n*N+i]*x[i];\n"
"xPart[t] = pSum;\n"
"}\n"
;
