const char* lu259_cl =
"__kernel void\n"
"LUFact(\n"
"__global double* x,\n"
"__global double* A,\n"
"__global double* L,\n"
"__global double* b,\n"
"__global double* y,\n"
"__global double* Acurr,\n"
"int N)\n"
"{\n"
"int tX = get_local_id(0);\n"
"int tY = get_local_id(1);\n"
"double denom;\n"
"if (tY == 0) {\n"
"Acurr[tX] = A[tY*N+tX];\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"if (tX == tY)\n"
"L[tY*N+tY] = 1;\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"denom = Acurr[tX];\n"
"if(tY > tX) {\n"
"double lval = A[tY*N+tX]/denom;\n"
"L[tY*N+tX] = lval;\n"
"lval = -lval;\n"
	"for(int i = tX+1; i < N; i++) {\n"
"A[tY*N+i] += lval*Acurr[i];\n"
"}\n"
"}\n"		
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"if(tY == tX+1) {\n"
"for(int i = tY; i < N; i++)\n"
"Acurr[i] = A[tY*N+i];\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"double yi = b[tY];\n"
"for(int i = 0; i < N; i++) {\n"
"if(i == tY) {\n"
"for(int j = 0; j < tY; j++) {\n"
"yi -= L[tY*N+j]*y[j];\n"
"}\n"
"y[tY] = yi;\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"}\n"
"double xi = y[tY];\n"
"for(int i = N-1; i >= 0; i--) {\n"
"if(i == tY) {\n"
"for(int j = tY+1; j < N; j++)\n"
"xi -= A[tY*N+j]*x[j];\n"
"x[tY] = xi/A[tY*N+tY];\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"}\n"
"}\n"
;
