const char* lu259_cl =
"__kernel void\n"
"LUFact(\n"
"__global double* x,\n"
"__global double* A,\n"
"__global double* L,\n"
"__global double* b,\n"
"__global double* y,\n"
"int width_matrix, int height_vector)\n"
"{\n"
"int tIndex = get_local_id(0);\n"
"__local double denom;\n"
"if (tIndex == 0)\n"
"denom = A[tIndex*width_matrix+tIndex];\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"L[tIndex*width_matrix+tIndex] = 1;\n"
"for (int i = tIndex+1; i < width_matrix; i++)\n"
"{\n"
"double lval = A[i*width_matrix+tIndex]/denom;\n"
"L[i*width_matrix+tIndex] = lval;\n"
"lval = -lval;\n"
"for(int k = tIndex+1; k < width_matrix; k++)\n"
"{\n"
"A[i*width_matrix+k] += lval*A[tIndex*width_matrix+k];\n"
"}\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"double yi = b[tIndex];\n"
"for(int j = 0; j < tIndex; j++)\n"
"{\n"
"yi -= L[tIndex*width_matrix+j]*y[j];\n"
"}\n"
"y[tIndex] = yi;\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"double xi = y[tIndex];\n"
"for(int j = tIndex+1; j < width_matrix; j++)\n"
"xi -= A[tIndex*width_matrix+j]*x[j];\n"
"x[tIndex] = xi/A[tIndex*width_matrix+tIndex];\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"}\n"
;
