const char* lu259_cl =
"#define N 512\n"
"__kernel void\n"
"LUFact(\n"
"__global double* x,\n"
"__global double* A,\n"
"__global double* L,\n"
"__global double* b,\n"
"__global double* y)\n"
"{\n"
"int tIndex = get_local_id(0);\n"
"double At[N];\n"
"double Lt[N];\n"
"for(int i = 0; i < N; i++)\n"
"At[i] = A[tIndex*N+i];\n"
"double denom;\n"
"__local double Acurr[N];\n"
"if (tIndex == 0) {\n"
"for(int i = 0; i < N; i++)\n"
"Acurr[i] = At[i];\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"Lt[tIndex] = 1;\n"
"for(int n = 0; n < N; n++) {\n"
"denom = Acurr[n];\n"
"if(tIndex > n) {\n"
"double lval = At[n]/denom;\n"
"Lt[n] = lval;\n"
"lval = -lval;\n"
"for(int i = n+1; i < N; i++) {\n"
"At[i] += lval*Acurr[i];\n"
"}\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE); // may be necessary\n"
"if(tIndex == n+1) {\n"
"for(int i = tIndex; i < N; i++)\n"
"Acurr[i] = At[i];\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE); // should be necessary	\n"
"}\n"
"double yi = b[tIndex];\n"
"for(int i = 0; i < N; i++) {\n"
"if(i == tIndex) {\n"
"for(int j = 0; j < tIndex; j++) {\n"
"yi -= Lt[j]*y[j];\n"
"}\n"
"y[tIndex] = yi;\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"}\n"
"double xi = y[tIndex];\n"
"for(int i = N-1; i >= 0; i--) {\n"
"if(i == tIndex) {\n"
"for(int j = tIndex+1; j < N; j++)\n"
"xi -= At[j]*x[j];\n"
"x[tIndex] = xi/At[tIndex];\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"}\n"
"}\n"
;
