const char* lu259_cl =
"__kernel void\n"
"LUFact(\n"
"__global float* x,\n"
"__global float* A,\n"
"__global float* L,\n"
"__global float* b,\n"
"__global float* y,\n"
"__global float* Acurr,\n"
"int N)\n"
"{\n"
"int tIndex = get_local_id(0);\n"
"float denom;\n"
"//__local float Acurr[N];\n"
"if (tIndex == 0) {\n"
"for(int i = 0; i < N; i++)\n"
"Acurr[i] = A[tIndex*N+i];\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"L[tIndex*N+tIndex] = 1;\n"
"for(int n = 0; n < N; n++) {\n"
"denom = Acurr[n];\n"
"if(tIndex > n) {\n"
"float lval = A[tIndex*N+n]/denom;\n"
"L[tIndex*N+n] = lval;\n"
"lval = -lval;\n"
"for(int i = n+1; i < N; i++) {\n"
"A[tIndex*N+i] += lval*Acurr[i];\n"
"}\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE); // may be necessary\n"
"if(tIndex == n+1) {\n"
"for(int i = tIndex; i < N; i++)\n"
"Acurr[i] = A[tIndex*N+i];\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE); // should be necessary	\n"
"}\n"
"float yi = b[tIndex];\n"
"for(int i = 0; i < N; i++) {\n"
"if(i == tIndex) {\n"
"for(int j = 0; j < tIndex; j++) {\n"
"yi -= L[tIndex*N+j]*y[j];\n"
"}\n"
"y[tIndex] = yi;\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"}\n"
"float xi = y[tIndex];\n"
"for(int i = N-1; i >= 0; i--) {\n"
"if(i == tIndex) {\n"
"for(int j = tIndex+1; j < N; j++)\n"
"xi -= A[tIndex*N+j]*x[j];\n"
"x[tIndex] = xi/A[tIndex*N+tIndex];\n"
"}\n"
"barrier(CLK_LOCAL_MEM_FENCE);\n"
"}\n"
"}\n"
;
